providers = ["php", "node"]

[variables]
NIXPACKS_NODE_VERSION = "20"
NIXPACKS_PHP_ROOT_DIR = "/app/public"

[phases.setup]
# WAJIB tambahkan "composer" ke dalam daftar nixPkgs agar command composer tidak found 127
nixPkgs = ["nodejs", "php83", "composer"]

[phases.install]
cmds = [
  "composer install --no-interaction --no-dev --optimize-autoloader",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

[phases.postbuild]
cmds = [
]